export const CATEGORY_OPTIONS = [
    { value: '디지털기기', label: '디지털기기' },
    { value: '생활가전', label: '생활가전' },
    { value: '가구/인테리어', label: '가구/인테리어' },
    { value: '생활/주방', label: '생활/주방' },
    { value: '유아동', label: '유아동' },
    { value: '유아도서', label: '유아도서' },
    { value: '여성의류', label: '여성의류' },
    { value: '여성잡화', label: '여성잡화' },
    { value: '남성패션/잡화', label: '남성패션/잡화' },
    { value: '뷰티/미용', label: '뷰티/미용' },
    { value: '스포츠/레저', label: '스포츠/레저' },
    { value: '취미/게임/음반', label: '취미/게임/음반' },
    { value: '도서', label: '도서' },
    { value: '티켓/교환권', label: '티켓/교환권' },
    { value: '가공식품', label: '가공식품' },
    { value: '건강기능식품', label: '건강기능식품' },
    { value: '반려동물용품', label: '반려동물용품' },
    { value: '식물', label: '식물' },
    { value: '기타 중고물품', label: '기타 중고물품' },
    { value: '삽니다', label: '삽니다' },
];