export const CATEGORY_OPTIONS = [
  { value: '1', label: '디지털기기' },
  { value: '2', label: '생활가전' },
  { value: '3', label: '가구/인테리어' },
  { value: '4', label: '생활/주방' },
  { value: '5', label: '유아동' },
  { value: '6', label: '유아도서' },
  { value: '7', label: '여성의류' },
  { value: '8', label: '여성잡화' },
  { value: '9', label: '남성패션/잡화' },
  { value: '10', label: '뷰티/미용' },
  { value: '11', label: '스포츠/레저' },
  { value: '12', label: '취미/게임/음반' },
  { value: '13', label: '도서' },
  { value: '14', label: '티켓/교환권' },
  { value: '15', label: '가공식품' },
  { value: '16', label: '건강기능식품' },
  { value: '17', label: '반려동물용품' },
  { value: '18', label: '식물' },
  { value: '19', label: '기타 중고물품' },
  { value: '20', label: '삽니다' },
];
